name: bbds_cli
description: Command line utility to pack a BBds file.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  
dependencies:
  args: ^2.0.0
  bbds_packer: 
    path: ../bbds_packer
  yaml: ^3.1.0


dev_dependencies:
  test: ^1.16.5